### ISSUE TITLE
Subprocess exited with error

### ISSUE THREAD

**Issue by MeoMayBe** [ForeverHaibara/Triple-SOS#17]
I have followed the instruction, but it failed due to this error:

Building wheel for cvxopt (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for cvxopt (pyproject.toml) did not run successfully.      
  │ exit code: 1
  ╰─> [238 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-312
      creating build\lib.win-amd64-cpython-312\cvxopt
      copying src\python\coneprog.py -> build\lib.win-amd64-cpython-312\cvxopt
      copying src\python\cvxprog.py -> build\lib.win-amd64-cpython-312\cvxopt 
      copying src\python\info.py -> build\lib.win-amd64-cpython-312\cvxopt    
      copying src\python\misc.py -> build\lib.win-amd64-cpython-312\cvxopt    
      copying src\python\modeling.py -> build\lib.win-amd64-cpython-312\cvxopt
      copying src\python\msk.py -> build\lib.win-amd64-cpython-312\cvxopt     
      copying src\python\printing.py -> build\lib.win-amd64-cpython-312\cvxopt
      copying src\python\solvers.py -> build\lib.win-amd64-cpython-312\cvxopt 
      copying src\python\_version.py -> build\lib.win-amd64-cpython-312\cvxopt
      copying src\python\__init__.py -> build\lib.win-amd64-cpython-312\cvxopt
      running build_ext
      building 'base' extension
      creating build\temp.win-amd64-cpython-312
      creating build\temp.win-amd64-cpython-312\Release
      creating build\temp.win-amd64-cpython-312\Release\src
      creating build\temp.win-amd64-cpython-312\Release\src\C
      D:\VSC\IDE\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\include" "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Include" -ID:\VSC\IDE\VC\Tools\MSVC\14.38.33130\include -ID:\VSC\IDE\VC\Auxiliary\VS\include "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /Tcsrc/C/base.c /Fobuild\temp.win-amd64-cpython-312\Release\src/C/base.obj
      base.c
      src/C/base.c(150): warning C4244: '=': conversion from 'Py_ssize_t' to 'double', possible loss of data
      src/C/base.c(279): warning C4244: 'function': conversion from 'Py_ssize_t' to 'long', possible loss of data
      src/C/base.c(419): warning C4244: 'initializing': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/base.c(516): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/base.c(517): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/base.c(518): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/base.c(660): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/base.c(661): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/base.c(688): warning C4244: 'initializing': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/base.c(816): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/base.c(781): warning C4244: 'initializing': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/base.c(782): warning C4244: 'initializing': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/base.c(891): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/base.c(911): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/base.c(1098): warning C4244: '=': conversion from 'Py_ssize_t' to 'double', possible loss of data
      src/C/base.c(1202): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/base.c(1472): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/base.c(1472): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/base.c(1650): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/base.c(1650): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/base.c(1912): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/base.c(1871): warning C4244: 'initializing': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/base.c(1872): warning C4244: 'initializing': conversion from 'Py_ssize_t' to 'int', possible loss of data
      D:\VSC\IDE\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\include" "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Include" -ID:\VSC\IDE\VC\Tools\MSVC\14.38.33130\include -ID:\VSC\IDE\VC\Auxiliary\VS\include "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /Tcsrc/C/dense.c /Fobuild\temp.win-amd64-cpython-312\Release\src/C/dense.obj
      dense.c
      src/C/dense.c(271): warning C4244: '=': conversion from 'Py_ssize_t' to 'double', possible loss of data
      src/C/dense.c(333): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(361): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(377): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(388): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(388): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(430): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(430): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(456): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(456): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(456): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(469): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(469): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(483): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(486): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(593): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(593): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(734): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(748): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(794): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(794): warning C4244: '+=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(795): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(795): warning C4244: '+=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(824): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(878): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(892): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(906): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(940): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(940): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(947): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(947): warning C4244: '+=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(948): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(948): warning C4244: '+=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(987): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(1005): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/dense.c(1022): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      D:\VSC\IDE\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\include" "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\Include" -ID:\VSC\IDE\VC\Tools\MSVC\14.38.33130\include -ID:\VSC\IDE\VC\Auxiliary\VS\include "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /Tcsrc/C/sparse.c /Fobuild\temp.win-amd64-cpython-312\Release\src/C/sparse.obj
      sparse.c
      src/C/sparse.c(243): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(424): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(471): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(570): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(603): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(613): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(622): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(641): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(656): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(663): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(679): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(698): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(707): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(716): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(745): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(748): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(755): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(761): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(769): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(791): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(809): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(815): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(837): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(896): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(922): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(846): warning C4244: 'initializing': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(863): warning C4244: 'initializing': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(863): warning C4244: 'initializing': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(946): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1018): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1058): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(961): warning C4244: 'initializing': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(977): warning C4244: 'initializing': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(977): warning C4244: 'initializing': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1086): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1095): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1082): warning C4244: 'initializing': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1124): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1138): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1120): warning C4244: 'initializing': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1166): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1167): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1163): warning C4244: 'initializing': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1207): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1208): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1204): warning C4244: 'initializing': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1274): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1275): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1306): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1307): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1327): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1328): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1363): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1364): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1384): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1402): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1419): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1422): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1466): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1477): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1483): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1501): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1504): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1571): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1610): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1643): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1644): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1685): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1686): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1710): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1714): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1755): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1759): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1792): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1823): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1851): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1858): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1924): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1944): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1955): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1982): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(1989): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(2089): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(2157): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(2187): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(2190): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(2220): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(2221): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(2241): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(2242): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(2276): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(2277): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(2310): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(2349): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(2359): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(2259): warning C4244: 'initializing': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(2308): warning C4244: 'initializing': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(2333): warning C4244: 'initializing': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(2569): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(2811): warning C4244: 'function': conversion from 'Py_ssize_t' to 'long', possible loss of data
      src/C/sparse.c(2812): warning C4244: 'function': conversion from 'Py_ssize_t' to 'long', possible loss of data
      src/C/sparse.c(2856): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(2857): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(2886): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(2919): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(2928): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(2941): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(2942): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(2943): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(3005): warning C4244: 'function': conversion from 'Py_ssize_t' to 'long', possible loss of data
      src/C/sparse.c(3006): warning C4244: 'function': conversion from 'Py_ssize_t' to 'long', possible loss of data
      src/C/sparse.c(3136): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(3154): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(3164): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(3164): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(3168): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(3174): warning C4244: 'return': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(3224): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(3476): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(3491): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(3641): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(3658): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(3671): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(3671): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(3680): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(3741): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(3757): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(3768): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(3768): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(3778): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(3913): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(3929): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(3942): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(3942): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(3953): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(4030): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(4044): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(4054): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(4054): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(4066): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(4106): warning C4244: 'initializing': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(4351): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(4351): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(4372): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(4372): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(4372): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(4434): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      src/C/sparse.c(4441): warning C4244: 'function': conversion from 'Py_ssize_t' to 'int', possible loss of data
      D:\VSC\IDE\VC\Tools\MSVC\14.38.33130\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:/usr/lib "/LIBPATH:C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\libs" "/LIBPATH:C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0" "/LIBPATH:C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.496.0_x64__qbz5n2kfra8p0\PCbuild\amd64" /LIBPATH:D:\VSC\IDE\VC\Tools\MSVC\14.38.33130\lib\x64 "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64" m.lib lapack.lib blas.lib /EXPORT:PyInit_base build\temp.win-amd64-cpython-312\Release\src/C/base.obj build\temp.win-amd64-cpython-312\Release\src/C/dense.obj build\temp.win-amd64-cpython-312\Release\src/C/sparse.obj /OUT:build\lib.win-amd64-cpython-312\cvxopt\base.cp312-win_amd64.pyd /IMPLIB:build\temp.win-amd64-cpython-312\Release\src/C\base.cp312-win_amd64.lib
      LINK : fatal error LNK1181: cannot open input file 'm.lib'
      error: command 'D:\\VSC\\IDE\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\link.exe' failed with exit code 1181
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cvxopt
Failed to build cvxopt
ERROR: Could not build wheels for cvxopt, which is required to install pyproject.toml-based projects

**Comment by ForeverHaibara** [comment]
Hi, @MeoMayBe .
I understand that you’re encountering an error while doing `pip install picos`, which is installing a dependency for my Python program. If you’re new to Python, there’s a workaround available. You can proceed without `pip install picos` and still launch the backend. Please note that only the SDPSOS method requires this package. Other methods such as StructuralSOS, LinearSOS, and SymmetricSOS will still work.

If you’re interested in resolving the error, it’s important to clarify that this issue arises during the installation of cvxopt, which is not directly related to my program. For further assistance, you might find this [discussion](https://github.com/robertmartin8/PyPortfolioOpt/issues/284) helpful, as it addresses a similar error.
